{% set name = "zimg" %}
{% set version = "3.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sekrit-twc/zimg/archive/release-{{ version }}.tar.gz
  sha256: be89390f13a5c9b2388ce0f44a5e89364a20c1c57ce46d382b1fcc3967057577
  patches:
    - libfile-link-to-zimg-dll.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('zimg', min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - automake  # [unix]
    - libtool  # [unix]
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libzimg${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\zimg.lib exit 1  # [win]

    # CFEP 18
    - test ! -f ${PREFIX}/lib/libzimg.a  # [not win]
    - if exist %LIBRARY_LIB%\zimg_static.lib exit 1  # [win]

about:
  home: https://github.com/sekrit-twc/zimg
  summary: Scaling, colorspace conversion, and dithering library
  description: |
    The "z" library implements the commonly required image processing basics of scaling,
    colorspace conversion, and depth conversion.
    A simple API enables conversion between any supported formats
    to operate with minimal knowledge from the programmer.
    All library routines were designed from the ground-up
    with correctness, flexibility, and thread-safety as first priorities.
    Allocation, buffering, and I/O are cleanly separated from processing,
    allowing the programmer to adapt "z" to many scenarios.
  license: WTFPL
  license_family: OTHER
  license_file: COPYING
  dev_url: https://github.com/sekrit-twc/zimg

extra:
  recipe-maintainers:
    - sshockwave
